### ISSUE TITLE
Cannot find module 'playfab-sdk/PlayFab' - supposed architectural problem

### ISSUE THREAD

**Issue by gmlion** [PlayFab/NodeSDK#89]
I think the documentation is incorrect, and possibly there's also some problems in the architecture of the plugin as a node module.
- Requiring PlayFab as per documentation
`var PlayFab = require("playfab-sdk/PlayFab");`
doesn't work:
`Error: Cannot find module 'playfab-sdk/PlayFab'`

Looking through the code, I suppose we should get a reference to the PlayFab object (and eventually any other PlayFab specific object) from main.js, which is where they're instantiated.
I managed to do so by exporting everything in main.js:
`module.exports = {
    PlayFab: PlayFab,
    PlayFabAdmin: PlayFabAdmin,
    PlayFabMatchmaker: PlayFabMatchmaker,
    PlayFabClient: PlayFabClient,
    PlayFabServer: PlayFabServer
}`

and importing the corresponding objects:
`var PlayFabRoot = require("playfab-sdk");
var PlayFab = PlayFabRoot.PlayFab;
var PlayFabServer = PlayFabRoot.PlayFabServer;`

- I think it's also wrong to suggest referencing to multiple PlayFab objects with multiple requires: since the object are stateful you're not getting the same singleton everytime, so, for example, the PlayFab object instance inside PlayFabServer is not the same you would get requiring it in the application code. This should work only if the library code is not a npm module: have you actually tested using the sdk as a npm module?

**Comment by pgilmorepf** [comment]
I will prepare a more thorough response to every point brought up above, but I'll start with this:
https://github.com/PlayFab/NodeSDK/tree/master/PlayFabTestingExample
This is our testing project.
In order to be published, the following steps must occur:
The vs solution must build with no errors (this is mostly to test the typescript bindings)
Then we execute a suite of tests via test.bat, which executes this file:
https://github.com/PlayFab/NodeSDK/blob/master/PlayFabTestingExample/PlayFabApiTests.js
Those tests must all execute, pass, and be relayed to our test-system, in order for our build to pass, which is a requirement for publishing (publishing to npm is another step in the same job).

From that testing file I can guarantee you a few things:
The test file does this:
var PlayFab = require("./Scripts/PlayFab/PlayFab");
And https://github.com/PlayFab/NodeSDK/blob/master/PlayFabSdk/Scripts/PlayFab/PlayFabClient.js does this:
var PlayFab = require("./PlayFab.js");

The test file assigns the titleId:
PlayFab.settings.titleId = TitleData.titleId;
And PlayFabClient.js reads it from the same object:
request.TitleId = PlayFab.settings.titleId != null ? PlayFab.settings.titleId : request.TitleId;

**Comment by gmlion** [comment]
While I'm sure require return the same object for multiple files _in the project_, it looks like it's not guaranteed when one of the require resides in a module:
http://justjs.com/posts/singletons-in-node-js-modules-cannot-be-trusted-or-why-you-can-t-just-do-var-foo-require-baz-init

There is the possibility this particular situation allows for your approach, but I suspect it's not idiomatic (and could brake in the future anyway) but I couldn't test it because I couldn't import the objects directly anyway.

I will join the slack channel in the following days to discuss the other topic, until then thank you for your time.

**Comment by pgilmorepf** [comment]
Hello again.

If you check the https://github.com/PlayFab/NodeSDK/tree/T3626 branch, you can see that we're working on an alternate version of the node package, which should resolve all of the issues we discussed.

Please take a look and let us know if it handles all the issues you found.

Thanks!

**Comment by pgilmorepf** [comment]
The latest published npm package solves the problem.

You can install the package, and then access it like this:

`
var playfab = require("playfab-sdk");

for(var each in playfab)
{
    console.log("Each : " + each);
}

for(var each in playfab.settings)
{
    console.log("Each.settings : " + each);
}
`

**Comment by yehtutwin** [comment]
var playfab = require("playfab-sdk");

var PlayFab = playfab.PlayFab;
var PlayFabClient = playfab.PlayFabClient;
